### ISSUE TITLE
Discord Publishing

### ISSUE THREAD

**Issue by DarthStormin** [Blackened76/SWGoH-Squad-Builder#14]
Ability to Select names and squads for TW zones to publish to Discord (akin to TB platooning in the TB sheet)

**Comment by Blackened76** [comment]
Thanks for the suggestions @DarthStormin!  I'm going to have to rely heavily on @PopGoesTheWza or someone with more knowledge of how the Google Sheets to Discord webhooks work.  I've actually been wanting to add this feature for a while.  It's definitely on the radar!
